### PR TITLE
Upload New Design Comps

### PR DESCRIPTION
**Pull request by brenthack35**
Here are my updated design comp pages for NAIFA. Please review and let me know if all is good to start the build.

### CODE REVIEW

**Comment by kendaleiv** [comment]
Do we want to include something in the footer that indicates our involvement with the website?

**Comment by bwarner22** [comment]
I think these are good and that we should review with Mike on Monday to get his thoughts

**Comment by brenthack35** [comment]
@kendaleiv Yeah, I will add in a Ritter Logo and say something like designed by or powered by RitterIM.

**Comment by hougasian** [comment]
@kendaleiv @brenthack35 Let's hold on "designed by or powered by RitterIM" for now - it's not really the business we're in (yet?)

**Pull request merged**
