### PR TITLE
NAIFA Design Comp Files

### PR DESCRIPTION
**Pull request by brenthack35**

### CODE REVIEW

**Comment by khalidabuhakmeh** [comment]
A good start. What do you think a `post` would look like? Something like the *About* page? Also, what will be in the carousel?

**Comment by khalidabuhakmeh** [comment]
Also the `naifa-logo.png` says *Greater Philadelphia Area*

**Comment by brenthack35** [comment]
The internal page comp is a layout for all internal pages including the posts page. I can create a posts page and a post archive page as well and push it up. That logo PNG was not supposed to be pushed up, that is the Philadelphia logo I grabbed to create the Harrisburg one. I will remove it from the assets folder

**Comment by bwarner22** [comment]
Definitely looking a lot better than what they have currently! 
Could we provide one for the calendar as well? I didn't see a link for that either on the homepage - unless that would be under links.

**Comment by brenthack35** [comment]
Sure thing! I will provide a calendar page and link for it in the Nav. I wanted to do a site map overhaul, half of those links they have are either not needed or can be combined.

**Comment by bwarner22** [comment]
Another thing that I just thought of - I know they want to appeal to both agents and consumers - not sure if we can show how that could be accomplished. A link? A post?

**Comment by brenthack35** [comment]
Good thought! I will ponder that and come up with a good solution in my comp to show them!

**Pull request closed without merging**
